package com.ai.rag;


import jakarta.annotation.PostConstruct;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

//@Component
public class RandomDataLoader {

    private final VectorStore vectorStore;

    public RandomDataLoader(VectorStore vectorStore){
        this.vectorStore = vectorStore;
    }

    @PostConstruct
    public  void loadSentencesIntoVectorStore(){
        List<String> sentences = List.of(
                "Java is a popular object-oriented programming language used for enterprise applications.",
                "Spring Boot simplifies the development of production-ready Java applications.",
                "Microservices divide large applications into smaller independently deployable services.",
                "REST APIs commonly use HTTP methods such as GET, POST, PUT, and DELETE.",
                "Docker containers package applications with their dependencies.",
                "Kubernetes automates deployment, scaling, and management of containerized applications.",
                "Git is a distributed version control system.",
                "Maven manages Java project dependencies and builds.",
                "React is a JavaScript library for building user interfaces.",
                "Angular is a TypeScript-based frontend framework.",
                "Python is widely used in data science and machine learning.",
                "Machine learning enables systems to learn patterns from data.",
                "Artificial intelligence aims to simulate human intelligence.",
                "Large language models are trained on massive text datasets.",
                "Embeddings convert text into numerical vectors.",
                "Vector databases store embeddings for similarity search.",
                "RAG stands for Retrieval Augmented Generation.",
                "Qdrant is a vector database optimized for semantic search.",
                "Ollama allows local execution of AI models.",
                "Gemma is an open-source language model developed by Google.",
                "The stock market enables companies to raise capital.",
                "A share represents ownership in a company.",
                "Bonds are debt instruments issued by governments or corporations.",
                "Inflation reduces the purchasing power of money.",
                "Central banks control monetary policy.",
                "Compound interest helps investments grow over time.",
                "Diversification reduces investment risk.",
                "Mutual funds pool money from multiple investors.",
                "Exchange traded funds are known as ETFs.",
                "The S&P 500 tracks major American companies.",
                "Bitcoin is the first decentralized cryptocurrency.",
                "Ethereum supports smart contracts.",
                "A bull market is characterized by rising prices.",
                "A bear market is characterized by falling prices.",
                "Market capitalization measures the total value of a company.",
                "Liquidity refers to how easily an asset can be sold.",
                "Risk and return are closely related in finance.",
                "A recession is a period of economic decline.",
                "GDP measures the value of goods and services produced.",
                "Interest rates influence borrowing and spending.",
                "The Earth revolves around the Sun.",
                "The Moon influences ocean tides.",
                "Mars is known as the Red Planet.",
                "Jupiter is the largest planet in the Solar System.",
                "Saturn is famous for its rings.",
                "Venus is the hottest planet in the Solar System.",
                "Mercury is the closest planet to the Sun.",
                "Neptune is known for strong winds.",
                "Uranus rotates on its side.",
                "Pluto is classified as a dwarf planet.",
                "The Milky Way is our home galaxy.",
                "A light-year measures distance in space.",
                "Black holes have extremely strong gravity.",
                "Supernovae occur when massive stars explode.",
                "The Sun is a main sequence star.",
                "Astronauts experience microgravity in space.",
                "NASA conducts space exploration missions.",
                "The James Webb Space Telescope studies distant galaxies.",
                "Dark matter cannot be directly observed.",
                "The universe is approximately 13.8 billion years old.",
                "DNA contains genetic instructions for living organisms.",
                "Cells are the basic units of life.",
                "The human body contains trillions of cells.",
                "Mitochondria are known as the powerhouses of cells.",
                "Proteins perform many biological functions.",
                "Photosynthesis converts sunlight into chemical energy.",
                "Plants absorb carbon dioxide from the atmosphere.",
                "Evolution explains the diversity of life.",
                "Natural selection was proposed by Charles Darwin.",
                "The human brain contains billions of neurons.",
                "The heart pumps blood throughout the body.",
                "Red blood cells transport oxygen.",
                "White blood cells help fight infections.",
                "The liver performs detoxification functions.",
                "The kidneys filter waste from the blood.",
                "Vaccines help prevent infectious diseases.",
                "Antibiotics are used to treat bacterial infections.",
                "Viruses require host cells to reproduce.",
                "Bacteria can exist in diverse environments.",
                "The immune system protects the body from pathogens.",
                "Tigers are the largest members of the cat family.",
                "Lions typically live in social groups called prides.",
                "Elephants are known for their intelligence and memory.",
                "Dolphins communicate using clicks and whistles.",
                "Blue whales are the largest animals ever known.",
                "Cheetahs are the fastest land animals.",
                "Penguins are flightless birds adapted to cold climates.",
                "Owls have excellent night vision.",
                "Eagles are powerful birds of prey.",
                "Sharks have existed for hundreds of millions of years.",
                "Octopuses are highly intelligent marine animals.",
                "Kangaroos are native to Australia.",
                "Polar bears depend on Arctic sea ice.",
                "Pandas primarily eat bamboo.",
                "Wolves are social predators.",
                "Honeybees play a crucial role in pollination.",
                "Ant colonies exhibit complex social behavior.",
                "Giraffes have the longest necks among mammals.",
                "Crocodiles are ancient reptiles.",
                "Sea turtles migrate long distances across oceans.",
                "Water freezes at zero degrees Celsius.",
                "Boiling water produces steam.",
                "Atoms consist of protons, neutrons, and electrons.",
                "Hydrogen is the most abundant element in the universe.",
                "Oxygen is essential for human respiration.",
                "Carbon forms the basis of organic life.",
                "Gravity attracts objects toward each other.",
                "Newton formulated the laws of motion.",
                "Einstein developed the theory of relativity.",
                "Energy cannot be created or destroyed.",
                "Sound travels through vibrations.",
                "Light behaves as both a particle and a wave.",
                "Electricity powers modern technology.",
                "Magnets have north and south poles.",
                "Chemical reactions transform substances.",
                "The periodic table organizes chemical elements.",
                "Acids and bases have different properties.",
                "Nuclear fusion powers the Sun.",
                "Quantum mechanics describes microscopic particles.",
                "Temperature measures thermal energy.",
                "The Great Wall of China is one of the world's largest structures.",
                "The Egyptian pyramids were built thousands of years ago.",
                "The Roman Empire influenced Western civilization.",
                "The Renaissance was a period of cultural revival.",
                "World War II ended in 1945.",
                "The Industrial Revolution transformed manufacturing.",
                "Ancient Greece contributed to philosophy and democracy.",
                "The printing press accelerated the spread of knowledge.",
                "The Silk Road connected Asia and Europe.",
                "The Declaration of Independence was signed in 1776.",
                "India is the world's most populous country.",
                "The Amazon rainforest contains immense biodiversity.",
                "Mount Everest is the highest mountain above sea level.",
                "The Pacific Ocean is the largest ocean.",
                "The Sahara is the largest hot desert.",
                "Tokyo is one of the world's largest cities.",
                "The Nile River is among the longest rivers.",
                "Antarctica is the coldest continent.",
                "Greenland is the world's largest island.",
                "The equator divides Earth into northern and southern hemispheres.",
                "Regular exercise improves cardiovascular health.",
                "Adequate sleep supports cognitive function.",
                "A balanced diet provides essential nutrients.",
                "Hydration is important for overall health.",
                "Strength training helps maintain muscle mass.",
                "Walking is a simple form of physical activity.",
                "Stress can affect both mental and physical health.",
                "Meditation may improve focus and relaxation.",
                "Obesity increases the risk of chronic diseases.",
                "Smoking is harmful to health.",
                "Excessive sugar consumption may contribute to health problems.",
                "Vitamin D supports bone health.",
                "Protein is important for muscle repair.",
                "Fiber supports digestive health.",
                "Mental health is an important aspect of well-being.",
                "Regular health checkups can detect diseases early.",
                "Sunlight helps the body produce vitamin D.",
                "Healthy habits often improve quality of life.",
                "The human body requires water for survival.",
                "Prevention is often more effective than treatment.",
                "Cybersecurity protects systems from digital threats.",
                "Encryption secures sensitive information.",
                "Cloud computing provides on-demand computing resources.",
                "Data centers host servers and applications.",
                "The Internet connects billions of devices worldwide.",
                "5G networks provide faster wireless communication.",
                "Blockchain is a distributed ledger technology.",
                "Smartphones combine communication and computing capabilities.",
                "Virtual reality creates immersive digital environments.",
                "Augmented reality overlays digital information onto the real world.",
                "Robotics combines engineering and computer science.",
                "Autonomous vehicles use sensors and artificial intelligence.",
                "Semiconductors are essential for modern electronics.",
                "Quantum computing aims to solve complex problems.",
                "Renewable energy includes solar and wind power.",
                "Solar panels convert sunlight into electricity.",
                "Wind turbines generate power from moving air.",
                "Electric vehicles reduce dependence on fossil fuels.",
                "Sustainable development balances economic and environmental goals.",
                "Technology continues to transform society."
        );

        List<Document> documentList = sentences.stream().map(Document::new).collect(Collectors.toList());
        vectorStore.add(documentList);

    }

}
