spring:
  application:
    name: MultiModel

  ai:
    ollama:
      chat:
        model: llama3.2:1b
    openai:
      api-key: ${OPEN_AI_KEY}

    ## for multi-model we need to set false, default its true
    chat:
      client:
        enabled: false

logging:
  level:
    org.springframework.ai: DEBUG
    #org.springframework.web.client: DEBUG
    org.springframework.web.client: TRACE
