spring:
  application:
    name: MultiModel

  ai:
    ollama:
      chat:
        model: llama3.2:1b
      embedding:
        options:
          model: nomic-embed-text
    openai:
      api-key: ${OPEN_AI_KEY}
      embedding:
        enabled: false

    ## for multi-model we need to set false, default its true
    chat:
      client:
        enabled: false
      memory:
        repository:
          jdbc:
            initialize-schema: always
    vectorstore:
      qdrant:
        initialize-schema : true
        host : localhost
        port : 6334
        collection-name : spring-vector
#Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/spring-ai
    username: root
    password: root

  docker:
    compose:
      stop:
        command: down

logging:
  level:
    org:
      springframework:
        ai:
          root: DEBUG  # Sets org.springframework.ai to DEBUG
          chat:
            client:
              advisor: DEBUG # Sets org.springframework.ai.chat.client.advisor to DEBUG
        web:
          client: TRACE # Sets org.springframework.web.client to TRACE
